pipeline:
  build_and_deploy_code:
    image: maven
    privileged: true
    when:
      branch: [master, develop]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./build-deploy.sh
